import { PrismaClient } from '@prisma/client';

const ProductCategory = {
  DOG_FOOD: 'DOG_FOOD',
  CAT_FOOD: 'CAT_FOOD',
  TOY: 'TOY',
  ACCESSORY: 'ACCESSORY',
  GROOMING: 'GROOMING',
  CAGE_BED: 'CAGE_BED',
  LEASH_COLLAR: 'LEASH_COLLAR',
};

const prisma = new PrismaClient();

async function generateProductId(): Promise<string> {
  for (let attempt = 0; attempt < 20; attempt += 1) {
    const id = String(Math.floor(100000 + Math.random() * 900000));
    const exists = await prisma.product.findUnique({ where: { id }, select: { id: true } });
    if (!exists) return id;
  }
  throw new Error('Could not generate a unique 6-digit product ID.');
}

async function main() {
  const products = [
    {
      name: 'Bát ăn tự động PUKY',
      slug: 'bat-an-tu-dong-puky',
      category: ProductCategory.ACCESSORY,
      targetSpecies: 'ALL',
      brand: 'PUKY',
      unit: 'cái',
      sellingPrice: 1290000,
      importPrice: 645000,
      salePrice: 1290000,
      rating: 4.7,
      reviewCount: 56,
      isFeatured: true,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop',
      ],
      description: 'Bát ăn tự động dung tích 4L, chia tối đa 6 bữa/ngày. Điều khiển từ xa qua ứng dụng, có camera ghi hình HD và loa thoại 2 chiều giúp bạn yên tâm chăm sóc thú cưng mọi lúc mọi nơi.',
      specifications: {
        'Dung tích': '4 lít',
        'Số bữa': 'Tối đa 6 bữa/ngày',
        'Camera': 'HD 1080p, đàm thoại 2 chiều',
        'Kết nối': 'WiFi 2.4GHz',
      },
    },
    {
      name: 'Royal Canin Corgi Adult 3kg',
      slug: 'royal-canin-corgi-adult-3kg',
      category: ProductCategory.DOG_FOOD,
      targetSpecies: 'DOG',
      brand: 'Royal Canin',
      unit: '3kg',
      sellingPrice: 1200000,
      importPrice: 600000,
      salePrice: 450000,
      rating: 4.8,
      reviewCount: 156,
      isFeatured: true,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1537151608828-ea2b117b6b86?w=600&h=600&fit=crop',
      ],
      description: 'Thuc an hat cao cap danh rieng cho cho Corgi truong thanh, ho tro khop va duy tri can nang ly tuong.',
    },
    {
      name: 'Whiskas thuc an meo vi ca ngu 1.2kg',
      slug: 'whiskas-ca-ngu-1-2kg',
      category: ProductCategory.CAT_FOOD,
      targetSpecies: 'CAT',
      brand: 'Whiskas',
      unit: '1.2kg',
      sellingPrice: 95000,
      importPrice: 47500,
      salePrice: 85000,
      rating: 4.7,
      reviewCount: 342,
      isFeatured: true,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1589883661923-6476cb0ae9f2?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=600&fit=crop',
      ],
      description: 'Thuc an kho vi ca ngu thom ngon, giau protein, phu hop voi nhieu giong meo.',
    },
    {
      name: 'Vong co da that cho meo mau hong',
      slug: 'vong-co-da-meo-mau-hong',
      category: ProductCategory.LEASH_COLLAR,
      targetSpecies: 'CAT',
      brand: 'PetStyle',
      unit: 'cai',
      sellingPrice: 220000,
      importPrice: 110000,
      salePrice: 180000,
      rating: 4.5,
      reviewCount: 78,
      isFeatured: true,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1601758066966-c3c47ca4eb0e?w=600&h=600&fit=crop',
      images: [],
      description: 'Vong co da mem co chuong nho, vua van va an toan cho meo.',
    },
    {
      name: 'Giuong o mem cho meo hinh tron',
      slug: 'giuong-o-mem-meo-hinh-tron',
      category: ProductCategory.CAGE_BED,
      targetSpecies: 'CAT',
      brand: 'CozyCat',
      unit: 'cai',
      sellingPrice: 300000,
      importPrice: 150000,
      salePrice: 250000,
      rating: 4.6,
      reviewCount: 34,
      isFeatured: true,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1545249390-6bdfa286032f?w=600&h=600&fit=crop',
      images: [],
      description: 'O ngu hinh tron sieu mem, chat lieu flannel de ve sinh.',
    },
    {
      name: 'Pedigree thuc an uot cho cho 12 goi',
      slug: 'pedigree-uot-cho-cho-12-goi',
      category: ProductCategory.DOG_FOOD,
      targetSpecies: 'DOG',
      brand: 'Pedigree',
      unit: '12 goi',
      sellingPrice: 145000,
      importPrice: 72500,
      salePrice: 129000,
      rating: 4.4,
      reviewCount: 201,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Can cau do choi cho meo long vu',
      slug: 'can-cau-do-choi-meo-long-vu',
      category: ProductCategory.TOY,
      targetSpecies: 'CAT',
      brand: 'PlayPet',
      unit: 'cai',
      sellingPrice: 45000,
      importPrice: 22500,
      salePrice: null,
      rating: 4.3,
      reviewCount: 89,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Sua tam cho cho 500ml huong phan',
      slug: 'sua-tam-cho-cho-500ml',
      category: ProductCategory.GROOMING,
      targetSpecies: 'DOG',
      brand: 'PetClean',
      unit: '500ml',
      sellingPrice: 120000,
      importPrice: 60000,
      salePrice: 95000,
      rating: 4.6,
      reviewCount: 145,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Bong cao su do choi cho cho',
      slug: 'bong-cao-su-cho-cho',
      category: ProductCategory.TOY,
      targetSpecies: 'DOG',
      brand: 'DogPlay',
      unit: 'cai',
      sellingPrice: 55000,
      importPrice: 27500,
      salePrice: null,
      rating: 4.2,
      reviewCount: 67,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Chuong sat cho cho size M',
      slug: 'chuong-sat-cho-cho-size-m',
      category: ProductCategory.CAGE_BED,
      targetSpecies: 'DOG',
      brand: 'PetHome',
      unit: 'cai',
      sellingPrice: 1500000,
      importPrice: 750000,
      salePrice: 1200000,
      rating: 4.5,
      reviewCount: 23,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Day dat cho tu thu 5m',
      slug: 'day-dat-cho-tu-thu-5m',
      category: ProductCategory.LEASH_COLLAR,
      targetSpecies: 'DOG',
      brand: 'SafeWalk',
      unit: 'cai',
      sellingPrice: 185000,
      importPrice: 92500,
      salePrice: 155000,
      rating: 4.4,
      reviewCount: 112,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&h=600&fit=crop',
      images: [],
    },

    {
      name: 'Cat ve sinh cho meo 10L huong tao',
      slug: 'cat-ve-sinh-meo-10l-huong-tao',
      category: ProductCategory.GROOMING,
      targetSpecies: 'CAT',
      brand: 'OdorBlock',
      unit: '10L',
      sellingPrice: 95000,
      importPrice: 47500,
      salePrice: 79000,
      rating: 4.5,
      reviewCount: 178,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1604542031658-5799ca5d7936?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Bat an inox chong truot cho thu cung',
      slug: 'bat-an-inox-chong-truot',
      category: ProductCategory.ACCESSORY,
      targetSpecies: 'ALL',
      brand: 'PetBowl',
      unit: 'cai',
      sellingPrice: 85000,
      importPrice: 42500,
      salePrice: 69000,
      rating: 4.4,
      reviewCount: 92,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1601758124096-1fd661873b5b?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Ao hoodie cho cho meo size S',
      slug: 'ao-hoodie-cho-cho-meo-size-s',
      category: ProductCategory.ACCESSORY,
      targetSpecies: 'ALL',
      brand: 'WarmPet',
      unit: 'cai',
      sellingPrice: 180000,
      importPrice: 90000,
      salePrice: 149000,
      rating: 4.1,
      reviewCount: 58,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Pate cho meo vi ga va ca hoi 80g',
      slug: 'pate-meo-ga-ca-hoi-80g',
      category: ProductCategory.CAT_FOOD,
      targetSpecies: 'CAT',
      brand: 'Me-O',
      unit: '80g',
      sellingPrice: 18000,
      importPrice: 9000,
      salePrice: 15000,
      rating: 4.6,
      reviewCount: 265,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1571566882372-1598d88abd90?w=600&h=600&fit=crop',
      images: [],
    },
    {
      name: 'Luoc chai long tu dong cho thu cung',
      slug: 'luoc-chai-long-tu-dong',
      category: ProductCategory.GROOMING,
      targetSpecies: 'ALL',
      brand: 'FurCare',
      unit: 'cai',
      sellingPrice: 135000,
      importPrice: 67500,
      salePrice: 109000,
      rating: 4.3,
      reviewCount: 121,
      isFeatured: false,
      isActive: true,
      imageUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&h=600&fit=crop',
      images: [],
    },
  ];

  const defaultCategories = [
    { name: 'Thức ăn cho chó', slug: 'DOG_FOOD' },
    { name: 'Thức ăn cho mèo', slug: 'CAT_FOOD' },
    { name: 'Đồ chơi thú cưng', slug: 'TOY' },
    { name: 'Phụ kiện thú cưng', slug: 'ACCESSORY' },
    { name: 'Chăm sóc & Vệ sinh', slug: 'GROOMING' },
    { name: 'Chuồng & Nệm ngủ', slug: 'CAGE_BED' },
    { name: 'Vòng cổ & Dây dắt', slug: 'LEASH_COLLAR' },
  ];

  console.log('Seeding categories...');
  for (const cat of defaultCategories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
  }
  console.log(`Seeded ${defaultCategories.length} categories`);

  console.log('Seeding products...');
  for (const product of products) {
    const existing = await prisma.product.findUnique({ where: { slug: product.slug }, select: { id: true } });
    await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: { ...product, id: existing?.id ?? await generateProductId() },
    });
  }
  console.log(`Seeded ${products.length} products`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
